name: patientpic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1


  photo_view: ^0.15.0
  http: ^0.13.3


  result_type: ^1.0.0
  dio: ^5.7.0
  file_picker: ^8.0.7
  open_file: ^3.5.4
  flutter_pdfview: ^1.3.2
  flutter_secure_storage: ^9.2.2
  uuid: ^4.5.0
  flutter_downloader: ^1.9.2
  cloud_firestore: ^5.3.0
  permission_handler: ^11.3.1
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  path_provider: ^2.0.1
  path: ^1.8.0

  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.5
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  firebase_storage: ^12.2.0
  firebase_app_check: ^0.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/download.png
    - assets/logo.png
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
