// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqvhfBOwGp7iCJL8j7oqWF7E0bb1GU-7g',
    appId: '1:800825364928:web:beb2c2a537d75d09133825',
    messagingSenderId: '800825364928',
    projectId: 'patientpic-2ee88',
    authDomain: 'patientpic-2ee88.firebaseapp.com',
    storageBucket: 'patientpic-2ee88.appspot.com',
    measurementId: 'G-2YQHLS7DR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1hM768AcaiVQKp-OwK0nvCqeo-taVDus',
    appId: '1:800825364928:android:eafe51dfebdaf632133825',
    messagingSenderId: '800825364928',
    projectId: 'patientpic-2ee88',
    storageBucket: 'patientpic-2ee88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhJ_PYPr6icJtHVNvwEPasnew5k3HwCWY',
    appId: '1:800825364928:ios:8e8a065a90b6c94f133825',
    messagingSenderId: '800825364928',
    projectId: 'patientpic-2ee88',
    storageBucket: 'patientpic-2ee88.appspot.com',
    iosBundleId: 'com.example.patientpic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhJ_PYPr6icJtHVNvwEPasnew5k3HwCWY',
    appId: '1:800825364928:ios:8e8a065a90b6c94f133825',
    messagingSenderId: '800825364928',
    projectId: 'patientpic-2ee88',
    storageBucket: 'patientpic-2ee88.appspot.com',
    iosBundleId: 'com.example.patientpic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqvhfBOwGp7iCJL8j7oqWF7E0bb1GU-7g',
    appId: '1:800825364928:web:65903b67d9aac7a2133825',
    messagingSenderId: '800825364928',
    projectId: 'patientpic-2ee88',
    authDomain: 'patientpic-2ee88.firebaseapp.com',
    storageBucket: 'patientpic-2ee88.appspot.com',
    measurementId: 'G-K21GL2FQWE',
  );
}
